version: '3.4'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=6 --timeout 120 --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - db2
      - db3

  db:
    image: postgres:17
    container_name: transaction-management-db-1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres-1/pgdata:/data
      - ./postgres-1/config:/config
      - ./postgres-1/archive:/var/lib/postgresql/archive
      - ./postgres-1/postgres-init-scripts:/docker-entrypoint-initdb.d  
    env_file:
      - ./.env.prod.db
    command: postgres -c 'config_file=/config/postgresql.conf'
    

  db2:
    image: postgres:17
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
      - ./postgres-2/pgdata:/data
      - ./postgres-2/config:/config
      - ./postgres-2/archive:/var/lib/postgresql/archive
    env_file:
      - ./.env.prod.db
    ports:
      - "5433:5432"
    command: postgres -c 'config_file=/config/postgresql.conf'


  db3:
    image: postgres:17
    volumes:
      - postgres_data3:/var/lib/postgresql/data/
      - ./postgres-3/pgdata:/data
      - ./postgres-3/config:/config
      - ./postgres-3/archive:/var/lib/postgresql/archive
    env_file:
      - ./.env.prod.db
    ports:
      - "5434:5432"
    command: postgres -c 'config_file=/config/postgresql.conf'


volumes:
  postgres_data:
  postgres_data2:
  postgres_data3:
