services:
  transactionmanagement:
    image: transactionmanagement
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:8080
    depends_on:
      - db
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=games

  volumes:
  postgres_data: